name: Build and deploy ASP.Net Core app to Azure Web App - ZodiacAGB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o C:\COMP4952Workspace\Lab 1 Zodiac\Zodiacs

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: C:\COMP4952Workspace\Lab 1 Zodiac\Zodiacs

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7FB190D74F8346B58095EA243EB758D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BF8072ED193C4A5AB989DA4032B2BE1E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EC5349E2CF66473685D571A89D0B1060 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ZodiacAGB'
          slot-name: 'Production'
          package: ./publish
